#!/usr/bin/env python3
"""
Quick script to run CARLA simulations generated by VTA.
This script helps you run CARLA simulations easily.
"""
import sys
import os
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

def check_carla_import():
    """Check if CARLA is installed."""
    try:
        import carla
        print(f"✓ CARLA is installed (version: {carla.__version__ if hasattr(carla, '__version__') else 'unknown'})")
        return True
    except ImportError:
        print("✗ CARLA is not installed!")
        print("\nTo install CARLA Python API:")
        print("  pip install carla")
        print("\nOr if you have CARLA installed locally:")
        print("  Windows: pip install -e \"C:\\CARLA\\WindowsNoEditor\\PythonAPI\\carla\\dist\\carla-*.egg\"")
        print("  Linux:   pip install -e \"/path/to/CARLA/PythonAPI/carla/dist/carla-*.egg\"")
        return False

def check_carla_server():
    """Check if CARLA server is running."""
    try:
        import carla
        client = carla.Client('localhost', 2000)
        client.set_timeout(2.0)
        client.get_world()
        print("✓ CARLA server is running on localhost:2000")
        return True
    except Exception as e:
        print("✗ CARLA server is not running!")
        print(f"  Error: {e}")
        print("\nTo start CARLA server:")
        print("  Windows: C:\\CARLA\\WindowsNoEditor\\CarlaUE4.exe -carla-rpc-port=2000")
        print("  Linux:   ./CARLA/CarlaUE4.sh -carla-rpc-port=2000")
        print("  macOS:   open /Applications/CARLA/CarlaUE4.app --args -carla-rpc-port=2000")
        return False

def list_available_simulations():
    """List all available CARLA simulation scripts."""
    sim_dir = project_root / "sim_output" / "carla"
    if not sim_dir.exists():
        print(f"✗ Simulation directory not found: {sim_dir}")
        return []
    
    scripts = list(sim_dir.glob("*.py"))
    if not scripts:
        print(f"✗ No simulation scripts found in {sim_dir}")
        return []
    
    print(f"\nAvailable simulation scripts ({len(scripts)}):")
    for i, script in enumerate(scripts, 1):
        print(f"  {i}. {script.name}")
    
    return scripts

def run_simulation(script_path):
    """Run a CARLA simulation script."""
    print(f"\n{'='*60}")
    print(f"Running simulation: {script_path.name}")
    print(f"{'='*60}\n")
    
    try:
        # Read and execute the script
        with open(script_path, 'r', encoding='utf-8') as f:
            script_code = f.read()
        
        # Execute the script
        exec(script_code, {'__name__': '__main__'})
        
        print(f"\n✓ Simulation completed successfully!")
        
    except KeyboardInterrupt:
        print("\n\n⚠ Simulation interrupted by user (Ctrl+C)")
    except Exception as e:
        print(f"\n✗ Simulation failed with error:")
        print(f"  {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    return True

def main():
    """Main function."""
    print("="*60)
    print("CARLA Simulation Runner - VTA")
    print("="*60)
    
    # Check CARLA installation
    if not check_carla_import():
        sys.exit(1)
    
    # Check CARLA server
    if not check_carla_server():
        print("\n⚠ Please start CARLA server first, then run this script again.")
        sys.exit(1)
    
    # List available simulations
    scripts = list_available_simulations()
    if not scripts:
        sys.exit(1)
    
    # Ask user to select simulation
    if len(sys.argv) > 1:
        # Script provided as argument
        script_name = sys.argv[1]
        script_path = project_root / "sim_output" / "carla" / script_name
        if not script_path.exists():
            print(f"✗ Script not found: {script_path}")
            sys.exit(1)
    else:
        # Interactive selection
        print("\nEnter script number to run (or 'q' to quit):")
        try:
            choice = input("> ").strip()
            if choice.lower() == 'q':
                print("Exiting...")
                sys.exit(0)
            
            script_index = int(choice) - 1
            if script_index < 0 or script_index >= len(scripts):
                print(f"✗ Invalid selection. Please choose 1-{len(scripts)}")
                sys.exit(1)
            
            script_path = scripts[script_index]
        except (ValueError, KeyboardInterrupt):
            print("\nExiting...")
            sys.exit(0)
    
    # Run simulation
    success = run_simulation(script_path)
    
    if success:
        print("\n" + "="*60)
        print("Simulation finished!")
        print("="*60)
    else:
        sys.exit(1)

if __name__ == '__main__':
    main()

